### ISSUE TITLE
After a new record is created the list doesen't refresh

### ISSUE THREAD

**Issue by gneils** [gneils/rec_keys_to_array#1]
Use any case and a record type with keys.  The list doesn't get updated after the new record is created.

**Comment by gneils** [comment]
Use the other file!

**Comment by davidpmerle** [comment]
In ADRC (CLONE) in BRAIN form, when a date is clicked, SIR crashes with the following error:

-----------   show values to update -----------
Database return code 240  Missing value is invalid for CASE ID/KEYFIELDS.

**Comment by davidpmerle** [comment]
Actually, SIR does not crash, but NAVIGATE.MAIN does
