### ISSUE TITLE
DCCPROCF.NAVIGATE.TESTING_VERSION crashes when a key date field is clicked 

### ISSUE THREAD

**Issue by davidpmerle** [gneils/rec_keys_to_array#2]
In the BRAIN form of ADRC (Clone), DCCPROCF.NAVIGATE.TESTING_VERSION crashes when a date is clicked in a key field with the error message of:

-----------   show values to update -----------
Database return code 240  Missing value is invalid for CASE ID/KEYFIELDS.

**Comment by gneils** [comment]
I reproduced it.  Thanks.  Will work on this one.

**Comment by gneils** [comment]
Not an issue with Nav.Main

ADRC and NACCUDS work together.  The NACCUDS GUI handles this.  

NACCUDS actually uses KEY2 for passing the value to the BRAIN screen.  This may be due to the position on the screen and that NACCUDS stuff uses the other list, which is probably KEY1.
